### ISSUE TITLE
Some location website links don't redirect from website (leading to 404)

### ISSUE THREAD

**Issue by Richie78321** [Zmwang622/Vaccinate-PA#44]
![image](https://user-images.githubusercontent.com/31116115/109603277-9d507400-7aef-11eb-91eb-556ff763d88c.png)
The Visit Website link in this example leads to a VaccinatePA 404

**Comment by Zmwang622** [comment]
~~could solution be leading every link with `https://`? We had this issue with the wiki too~~ Saw the image, definitely should look into automating the process somehow.

**Comment by Richie78321** [comment]
@Zmwang622 Good enough solution is to prepend `http://` protocol to link if no protocol is specified

**Comment by Richie78321** [comment]
Just deployed
